//created on: Jun 3, 2012
package main.solver;
	dialect "java"

//パッケージのインポート
import org.drools.planner.core.score.buildin.hardandsoft.HardAndSoftScoreHolder;
import org.drools.planner.core.score.constraint.IntConstraintOccurrence;
import org.drools.planner.core.score.constraint.ConstraintType;

import main.domain.Course;
import main.domain.Day;
import main.domain.Classroom;
import main.domain.DayWeek;
import main.domain.Schedule;
import main.domain.Week
import main.domain.CourseTotalSize;
import main.domain.BlockedClassroom;

//グローバル変数の宣言
global HardAndSoftScoreHolder scoreHolder;

// ############################################################################
// ハード制約
// ############################################################################

//ルール①：開催日程は重複してはならない
rule "classroomOccupancy"
    when
        $leftSchedule : Schedule($leftId : scheduleID, $classroom : classroom)
        //rightSchedule not being held between active time of leftSchedule
        $rightSchedule : Schedule(scheduleID > $leftId, conflictDayCheck($leftSchedule) == true, classroom.equals($classroom))
        
    then
    	//System.out.println("classroomOccupancy @" + $leftSchedule.toString() + " & " + $rightSchedule.toString());
        insertLogical(new IntConstraintOccurrence("classroomOccupancy", ConstraintType.NEGATIVE_HARD,
                1,
                $leftSchedule, $rightSchedule));
end

//ルール②：コース定員が教室定員を上回ってはならない
rule "overCapacity"
    when
        $schedule : Schedule(classroom.capacity < course.eSize)
        
    then
        insertLogical(new IntConstraintOccurrence("overCapacity", ConstraintType.NEGATIVE_HARD,
                1,
                $schedule));
end

//ルール③：コースを営業日以外に開催してはならない
rule "notFinishInWeek"
    when
        $schedule : Schedule( finishInWeek == false )       
    then
        insertLogical(new IntConstraintOccurrence("notFinishInWeek", ConstraintType.NEGATIVE_HARD,
                1,
                $schedule));
end

//ルール④：PCの必要なコースをPCの無い教室に割り当ててはならない
rule "pcRequirement"
    when
        $schedule : Schedule(course.PC != null, classroom.PC != course.PC)
    then
        insertLogical(new IntConstraintOccurrence("pcRequirement", ConstraintType.NEGATIVE_HARD,
                1,
                $schedule));
end

//ルール⑤：コースが要求するPCの種類が、教室が所有するPCの種類と違ってはならない
rule "pcTypeRequirement"
	when
		$schedule : Schedule(course.PC != null, checkPCRequirement() == false)
	then
	 insertLogical(new IntConstraintOccurrence("pcTypeRequirement", ConstraintType.NEGATIVE_HARD,
                1,
                $schedule));
end

//ルール⑥：コースに指定教室がある場合は、指定教室以外の教室に割り当ててはならない
rule "fixedRoomRequirement"
	when
		$schedule : Schedule(checkFixedRoomRequirement() == false)
	then
		//System.out.println("fixedRoomRequirement");
	 insertLogical(new IntConstraintOccurrence("fixedRoomRequirement", ConstraintType.NEGATIVE_HARD,
                1,
                $schedule));
end

//ルール⑦：コース定員を教室定員とするものに関して、計画後の総定員数が目標総定員数を下回ってはならない
rule "totalSizeRequirement-check"
	when	
		$courseTotalSize : CourseTotalSize($course : course, $totalSize : totalSize)
		accumulate(
			 Schedule( course.equals($course) == true , $size : classroom.getCapacity);
				$total : sum($size);
				$total < $totalSize)
	then
		//System.out.println("total of " + $course.toString() + " " + 
		//$total + " "  + $totalSize);
	 	insertLogical(new IntConstraintOccurrence("totalSizeRequirement-check", ConstraintType.NEGATIVE_HARD,
                1,
                $courseTotalSize));
end

//ルール⑧：ブロックされている教室にコースを割り当ててはならない
rule "classroomBlock"
	when
		$blockedClassroom : BlockedClassroom($classroom : classroom)
		$schedule : Schedule(classroom.equals($classroom) == true, 
			conflictDayCheck($blockedClassroom) == true)
	then	
		insertLogical(new IntConstraintOccurrence("classroomBlock", ConstraintType.NEGATIVE_HARD,
                1,
                $schedule));
end

//ルール⑨：同じコースの開催開始日が同じになってはならない
rule "SameCourseDayConflict"
	when
        $leftSchedule : Schedule($leftID : scheduleID, $leftCourse : course ,$leftDay : day)
        //rightSchedule not being held between active time of leftSchedule
        $rightSchedule : Schedule(scheduleID > $leftID, course.equals($leftCourse) == true, day.equals($leftDay) == true)
        
    then
    	//System.out.println("SameCourseDayConflict @" + $leftSchedule.toString() + " & " + $rightSchedule.toString());
        insertLogical(new IntConstraintOccurrence("SameCourseDayConflict", ConstraintType.NEGATIVE_HARD,
                1,
                $leftSchedule, $rightSchedule));
end
/*
// ############################################################################
// ソフト制約
// ############################################################################

//ルール①：教室定員とコース定員が近い方がよい
//（教室定員-コース定員）を減点する。

rule "roomOptimization"
    when
        $classroom : Classroom($capacity : capacity)
        $schedule : Schedule(classroom.equals($classroom) == true, course.geteSize()!= 0 , $eSize : course.geteSize())
    then
        insertLogical(new IntConstraintOccurrence("roomOptimization", ConstraintType.NEGATIVE_SOFT,
                ($capacity-$eSize),
                $classroom, $schedule));
				//System.out.println("Schedule" + $schedule.toString());
				//System.out.println("classroom" + $classroom.toString());

end

//ルール②：開催期間が四日のコースは火曜日に優先的に開催する。
//火曜日以外に割り当てた場合に1点減点する

rule "favoriteDayWeek-length4-Tuesday"
    when
        $schedule : Schedule(course.getLength() == 4, day.getDayweek().getDayweek != 1)
    then
        insertLogical(new IntConstraintOccurrence("favoriteDayWeek-length4-Tuesday", ConstraintType.NEGATIVE_SOFT,
                1,
                $schedule));
				//System.out.println("Schedule" + $schedule.toString());
				
end

//ルール③：開催期間が3日のコースの開催開始日は、月曜日か水曜日に優先的に開催する。
//月曜日・水曜日以外に割り当てた場合に1点減点する。

rule "favoriteDayWeek-length3-Monday,Wednesday"
    when
        $schedule : Schedule(course.getLength() == 3, day.getDayweek().getDayweek != 0 && day.getDayweek().getDayweek != 2)
    then
        insertLogical(new IntConstraintOccurrence("favoriteDayWeek-length3-Monday,Wednesday", ConstraintType.NEGATIVE_SOFT,
                1,
                $schedule));
				//System.out.println("Schedule" + $schedule.toString());
				end
				
//ルール④：開催期間が2日のコースの開催開始日は、月曜日か木曜日に優先的に開催する。
//月曜日・木曜日以外に割り当てた場合に1点減点する。

rule "favoriteDayWeek-Monday,Thursday"
    when
        $schedule : Schedule(course.getLength() == 2, day.getDayweek().getDayweek != 0 && day.getDayweek().getDayweek != 3)
    then
        insertLogical(new IntConstraintOccurrence("favoriteDayWeek-Friday", ConstraintType.NEGATIVE_SOFT,
                1,
                $schedule));
				//System.out.println("Schedule" + $schedule.toString());
				end		

*/
// ############################################################################
// スコアの計算
// ############################################################################

//ハード制約のスコア計算
rule "hardConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $hardTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_HARD, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        )
    then
        scoreHolder.setHardConstraintsBroken($hardTotal.intValue());
end

//ソフト制約のスコア計算
rule "softConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $softTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_SOFT, $weight : weight),
            sum($weight) // Vote for http://jira.jboss.com/jira/browse/JBRULES-1075
        )
    then
        scoreHolder.setSoftConstraintsBroken($softTotal.intValue());
end



